### ISSUE TITLE
Suggest Use Ternaries vs Boolean

### ISSUE THREAD

**Issue by calendee** [jonasmerlin/astro-seo#1]
In `SEO.astro`, this pattern is used:

```
{ title && <title>{title}</title> }
```

In some circumstances (admittedly uncommon), this can cause issues with rendering. I've personally run into this myself.

Id' suggest this pattern instead:

```
{ title ? <title>{title}</title> : null }
```

I'd be happy to make a PR for this if you'd like.

Reference: https://kentcdodds.com/blog/use-ternaries-rather-than-and-and-in-jsx

**Comment by jonasmerlin** [comment]
Thank you for bringing this to my attention! No need to PR, I will fix this immediately and release a new version.

**Comment by jonasmerlin** [comment]
This is done in v0.3.7
