### ISSUE TITLE
Standard Formatting

### ISSUE THREAD

**Issue by justinnoel** [jonasmerlin/astro-seo#29]
Would you be willing to accept a PR for adding either a [Prettier](https://prettier.io) configuration or [editorconfig](https://editorconfig.org) for this project?

Either would make it much easier for others to contribute without constantly making changes to the spaces, tabs, etc.

I'd be happy to submit a PR using either based on your preferences. I personally prefer prettier, but it does require more tooling on the developer side. Most IDEs are already 100% aware and compliant with editorconfig.

May I suggest these configurations based on your existing code:

**Prettier**

```
{
	"printWidth": 80,
	"semi": true,
	"singleQuote": false,
	"trailingComma": "all",
	"useTabs": true
}
```

**editorconfig**

```
# EditorConfig helps developers define and maintain consistent
# coding styles between different editors and IDEs
# editorconfig.org

root = true

[*]
indent_style = tab
indent_size = 2
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

[*.{astro,js,jsx,ts,tsx}]
quote_type = double
```

**NOTE**: In each, I have use tabs as the indentation vs spaces. Tabs have some significant accessibility benefits over spaces. Also, I used double quotes as your code already seems to have them. 

P.S. editorconfig does not officially recognize`quote_type` but many IDEs respect this setting.

**Comment by jonasmerlin** [comment]
@justinnoel Sorry I didn't see this sooner, there really seems to something wrong with my GitHub notification settings as I didn't get a notification for this. I would be very happy to accept a PR for this! Would it make sense to have both configs?

**Comment by justinnoel** [comment]
@jonasmerlin Ugh.... I took forever to get back to this. 

It's really best to only choose `.editorconfig` **OR** Prettier.

**Comment by jonasmerlin** [comment]
@justinnoel Alright, then let's go with Prettier I'd say!

**Comment by jonasmerlin** [comment]
@justinnoel Runnign `npm run format` formats files according to the astro rules by now. So I'll close this issue. If you're missing something, feel free to reopen.
