### ISSUE TITLE
Tags aren't being added

### ISSUE THREAD

**Issue by yavko** [jonasmerlin/astro-seo#33]
For some reason every single twitter tag, og:description, every single article tag except for section aren't being added idk why. Is it a bug, I think? Is it me maybe I don't think so tho.

heres the source: https://github.com/yavko/website
The head output
![image](https://user-images.githubusercontent.com/15178513/156688964-51f5a974-034c-4139-8415-b00e83105997.png)

Does anyone know what it could be?

**Comment by alex-grover** [comment]
@yavko it seems like this issue was resolved on your end, can it be closed?

**Comment by yavko** [comment]
> @yavko it seems like this issue was resolved on your end, can it be closed?

Sure
