### ISSUE TITLE
Cannot read properties of undefined (reading 'href')  with Astro v0.26

### ISSUE THREAD

**Issue by philschonholzer** [jonasmerlin/astro-seo#36]
[From the Migration docs](https://docs.astro.build/en/migrate/#updated-astrorequest-api)
`Astro.request` has been changed to a standard Request object.

- Move `Astro.request.canonicalURL` to `Astro.canonicalURL`

Causes the following ERROR 
```
Cannot read properties of undefined (reading 'href')
TypeError: Cannot read properties of undefined (reading 'href')
    at /node_modules/astro-seo/src/SEO.astro:106:28
    at renderToString (/node_modules/astro/dist/runtime/server/index.js:329:27)
    at Module.renderComponent (/node_modules/astro/dist/runtime/server/index.js:125:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by jonasmerlin** [comment]
Thanks for bringing this to my attention @philschonholzer ! Fixed in [v0.5.0](https://www.npmjs.com/package/astro-seo/v/0.5.0)
