### ISSUE TITLE
Add support for Twitter, Open Graph/Facebook

### ISSUE THREAD

**Issue by FlipFloop** [jonasmerlin/astro-seo#47]
Like here: [https://metatags.io/](https://metatags.io/).

**Comment by FlipFloop** [comment]
Like here: https://metatags.io/

**Comment by jonasmerlin** [comment]
@FlipFloop I'm not sure what you mean. The link doesn't really help either. You can already add OpenGraph as well as Twitter specific tags. See the documentation on [supported props.](https://github.com/jonasmerlin/astro-seo#supported-props)

**Comment by jonasmerlin** [comment]
Since the rest of the previously unsupported Twitter tags landed in 0.7.0 I'll close this for inactivity for now. If you're missing something, feel free to reopen!
