### ISSUE TITLE
Setting charset within Extend

### ISSUE THREAD

**Issue by djmtype** [jonasmerlin/astro-seo#48]
Setting `meta: [{ name: "charset", charset: "utf-8" }]` within the `extend` object doesn't produce the correct results. 

Results render as `<meta content="utf-8" name="charset">`. 
The valid result should be `<meta charset="utf-8">`.

Unfortunately, setting `meta: [{ charset: "utf-8" }]` is invalid and produces no result.

**Comment by jonasmerlin** [comment]
@djmtype Thanks for reporting this! I will look into it ASAP.

**Comment by jonasmerlin** [comment]
@djmtype I added the `charset` property in 0.6.1 to set this correctly. With this I will close this issue, but feel free to write here if this doesn't solve your problem.
