### ISSUE TITLE
Please consider providing a way to disable the same title warning

### ISSUE THREAD

**Issue by maxcountryman** [jonasmerlin/astro-seo#61]
Specifically, [this line](https://github.com/jonasmerlin/astro-seo/blob/548a6eabc71217aaea06497207bca33cace358ce/src/SEO.astro#L99).

It's quite opinionated to suggest the OG title should not be the same as the page title: it entirely depends on the page and application. (I understand the point that the linked Tweet is making but it's not relevant to my use case, which uses the heading as the page title and therefore both title and OG title are the same value.)

If it were me, I would remove this altogether and leave it up to the user to decide how they want to configure their site.

<img width="1402" alt="Screenshot 2023-02-21 at 4 51 50 PM" src="https://user-images.githubusercontent.com/74351/220492474-b52f3854-b20e-4bab-ad0b-992e1e69155d.png">

**Comment by jonasmerlin** [comment]
> If it were me, I would remove this altogether and leave it up to the user to decide how they want to configure their site.

[Are you so sure about that? 😜](https://user-images.githubusercontent.com/5182256/221129596-99efe6ad-d4d2-4b8e-ba47-643b9e86bd7a.png)

Just kidding, really. Having an option to disable it is a fair point, I'll try to put a toggle in with the next version.

**Comment by raulfdm** [comment]
That would be great, indeed.

Either have a config option to disable that or warn once. I do want my `title` and `og:title` to be the same.

**Comment by jonasmerlin** [comment]
@raulfdm Sorry for the delay, but this has now landed in 0.7.2

You can pass `surpressWarnings={true}` and it should hide the warnings!

**Comment by raulfdm** [comment]
Thanks @jonasmerlin . Worked like a charm
