### ISSUE TITLE
how do you make the name logo, i think the astro-seo title logo is nice

### ISSUE THREAD

**Issue by woxixiulayin** [jonasmerlin/astro-seo#66]

**Comment by jonasmerlin** [comment]
@woxixiulayin Haha, thanks, glad you like it! Most of the heavy lifting is done by the Astro Logo itself I'd say–the "A" with the flame is all done by them. 

I used Figma to write out "Astro SEO". I then downloaded the Astro logo and replaced the initial, blank A with that logo. I then set the fill of the "SEO" part to be a gradient. (See attached image.) Then I exported it as a .png, uploaded it to GH inside the repo and then used the URL of the uploaded file inside the README.

<img width="1223" alt="Screenshot 2023-04-25 at 10 23 25" src="https://user-images.githubusercontent.com/5182256/234218743-6b7c5081-5136-4669-959c-53c50181cbc9.png">
