### ISSUE TITLE
localized version of a webpage

### ISSUE THREAD

**Issue by C0casio45** [jonasmerlin/astro-seo#67]
ref : https://developers.google.com/search/docs/specialty/international/localized-versions?hl=fr

```
<link rel="alternate" hreflang="en-gb"
       href="https://en-gb.example.com/page.html" />
  <link rel="alternate" hreflang="en-us"
       href="https://en-us.example.com/page.html" />
  <link rel="alternate" hreflang="en"
       href="https://en.example.com/page.html" />
  <link rel="alternate" hreflang="de"
       href="https://de.example.com/page.html" />
 <link rel="alternate" hreflang="x-default"
       href="https://www.example.com/" />
```

This feature can be implemented by using an array as input or defining each country code and giving the url (following next example)

```
<SEO
   alternate= {{
       en: "https://en.example.com/page.html",
       en_US: "https://en-us.example.com/page.html",
       de: "https://de.example.com/page.html",
       default: "https://www.example.com/"
   }}
/>
```

**Comment by C0casio45** [comment]
Sounds great, I am working on it this week end

**Comment by C0casio45** [comment]
done #68

**Comment by C0casio45** [comment]
Hey @jonasmerlin , Waiting for your approval

**Comment by jonasmerlin** [comment]
Hey @C0casio45, sorry I dropped the ball on this one. Only saw your PR today. Thank you for looking into this! I fixed a few issues with your PR, so if you're interested what has changes, take a look.

I will release a new version with the changes.
