### ISSUE TITLE
💡 Feature Request: Type extend.link

### ISSUE THREAD

**Issue by Marius-Romanus** [jonasmerlin/astro-seo#69]
Hello, it would be nice if the Link could be passed an optional parameter that is the "type", to be able to do, for example:

`<link rel="icon" type="image/svg+xml" href="/favicon.svg" />`

Greetings!

**Comment by jonasmerlin** [comment]
Hey @Marius-Romanus, this should already be possible. Just do the following:

```
<SEO
      extend={{ link: [{ rel: "icon", href: "/favicon.ico", type:"image/svg+xml" }] }}
/>
```

**Comment by Marius-Romanus** [comment]
It works perfectly, thanks!
