### ISSUE TITLE
The media attribute is ignored when included in extend.meta

### ISSUE THREAD

**Issue by jasontyping** [jonasmerlin/astro-seo#75]
Since astro-seo does not have built in support for meta elements with the name "theme-color", the preferred method to include those meta elements would be to use extend.meta. Those meta elements can use a "media" attribute.

Extending the meta element in astro-seo would look something like this:
`{
    name: "theme-color",
    media: "(prefers-color-scheme: dark)",
    content: theme_color_dark
},`

However, astro-seo seems to ignore the media attribute so that the output will just look something like this, missing the media attribute:
`<meta content="#010101" name="theme-color">`

Workaround is just to enter the meta tag the old fashioned way in the source. But perhaps astro-seo can support this use case.

**Comment by jonasmerlin** [comment]
Hey @jasontyping, thank you for your feedback! I think this request is very reasonable, but since there is an existing workaround and I sadly don't have enough time to add features to `astro-seo` right now, I would have to count on someone creating a PR for this. Maybe you want to give it a try?

**Comment by jasontyping** [comment]
Yes, I have this update in PR #78.
