### ISSUE TITLE
Link 'sizes' property is DOMTokenList type not string

### ISSUE THREAD

**Issue by gvkhna** [jonasmerlin/astro-seo#87]
Here's an error:

Turns out HTMLLinkElement property 'sizes' is set to DOMTokenList which isn't meant to be serialized/deserialized. I think the best course of action is to override the type to string.

<img width="1031" alt="Screenshot 2024-01-31 at 10 28 48 AM" src="https://github.com/jonasmerlin/astro-seo/assets/222124/fddb724f-d22a-48b2-b8f2-df8f2e46ed96">

**Comment by jonasmerlin** [comment]
Hey @gvkhna, thank you for reporting this. Would you be willing to submit a PR for this?

**Comment by gvkhna** [comment]
That should be all that is needed but there is lack of instructions for building/testing and I don't have time to work on this further. If you can take a look that would be great. Thanks!
